ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal NUMERIC(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_pix NUMERIC(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_coupon NUMERIC(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS discount_total NUMERIC(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_final NUMERIC(10,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS coupon_code_applied TEXT;
